version: '3.9'

services:
  telegram-bot:
    container_name: snearl
    working_dir: /snearl
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python -m snearl"